org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# Avoids kapt incremental compilation issues with Hilt on Kotlin 1.9.x
kotlin.incremental.useClasspathSnapshot=false
# Required when itext7 or other Java libs ship duplicate META-INF resources
android.enableJetifier=false
